on:
  workflow_call:
    inputs:
      distro:
        required: true
        default: 'debian'
        type: string
      codenames:
        description: 'Stringified JSON object listing target distro codenames'
        required: true
        default: '["bullseye"]'
        type: string
      architectures:
        description: 'Stringified JSON object listing target architectures'
        required: true
        default: '["amd64"]'
        type: string
      release:
        required: false
        default: false
        type: boolean
    secrets:
      deploy-host:
        required: false
      deploy-user:
        required: false
      deploy-key:
        required: false

jobs:
  build:
    name: 'Build FFmpeg'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        release: ${{fromJson(inputs.codenames)}}
        arch: ${{fromJson(inputs.architectures)}}
  
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Install make and mmv
        run: sudo apt-get install make mmv

      - name: Build Linux
        run: ./build-sid ${{ matrix.release }} ${{ matrix.arch }} dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ inputs.distro }}-${{ matrix.release }}-${{ matrix.arch }}
          path: dist

  publish:
    name: Publish Release
    if: ${{ inputs.release }}
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      fail-fast: true
      matrix:
        release: ${{fromJson(inputs.codenames)}}
        arch: ${{fromJson(inputs.architectures)}}

    steps:
      - name: Set Versions
        uses: actions/github-script@v6.3.3
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            const dash_index = no_v.lastIndexOf('-')
            const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
            core.setOutput('tag', tag)
            core.setOutput('no-v', no_v)
            core.setOutput('no-dash', no_dash)

      - name: Download Artifacts
        uses: actions/download-artifact@v3.0.1
        with:
          name: ${{ inputs.distro }}-${{ matrix.release }}-${{ matrix.arch }}
          path: artifact

      - name: Prepare Release Assets
        run: |-
          pushd artifact
          find * -type f -name "*.deb" | while read file; do
            sha256sum "${file}" | tee "${file}.sha256sum"
          done
          popd
          
      - name: Upload GH Release Assets
        uses: shogo82148/actions-upload-release-asset@v1.6.3
        with:
          upload_url: ${{ github.event.release.upload_url }}
          overwrite: true
          asset_path: |
            ./artifact/**/*.zip
            ./artifact/**/*.deb
            ./artifact/**/*.sha256sum

